### PR TITLE
Fix legacy seaice extent and volume diagnostics

### LINKED ISSUE #2110: Seaice extent and volume failing
### machine

Lumi

### catalog

climatedt-phase1

### version

main

### What happened?

Both seaice volume and extent diagnostics fail with the following error message.
This is also the cause of #2103 

### Code to reproduce the issue

```python
python ~/work/AQUA/diagnostics/seaice/cli/cli_seaice.py --model IFS-NEMO --exp ssp370 --source lra-r100-monthly --outputdir /pfs/lustrep3/projappl/project_465000454/jvonhar/aqua-analysis/output_test/climatedt-phase1/IFS-NEMO/ssp370/r1/seaice_volume --config ~/.aqua/diagnostics/seaice/cli/config_Volume.yaml --nworkers 4 --catalog climatedt-phase1 --realization r1 -l DEBUG &> /pfs/lustrep3/projappl/project_465000454/jvonhar/test/timeseries/seaice_volume.log
```

and

```
 python ~/work/AQUA/diagnostics/seaice/cli/cli_seaice.py --model IFS-NEMO --exp ssp370 --source lra-r100-monthly --outputdir /pfs/lustrep3/projappl/project_465000454/jvonhar/aqua-analysis/output_test/climatedt-phase1/IFS-NEMO/ssp370/r1/seaice_extent  --config ~/.aqua/diagnostics/seaice/cli/config_Extent.yaml --nworkers 4 --catalog climatedt-phase1 --realization r1 -l DEBUG >&/pfs/lustrep3/projappl/project_465000454/jvonhar/test/timeseries//seaice_extent.log
```

### Error messages

```
Traceback (most recent call last):
  File "/users/jvonhar/work/AQUA/diagnostics/seaice/cli/cli_seaice.py", line 151, in <module>
    analyzer.run()
  File "/pfs/lustrep3/projappl/project_465000454/jvonhar/AQUA/diagnostics/seaice/seaice/seaice_class.py", line 429, in run
    self.computeVolume()
  File "/pfs/lustrep3/projappl/project_465000454/jvonhar/AQUA/diagnostics/seaice/seaice/seaice_class.py", line 529, in computeVolume
    myVolume = (sivol_mask * areacello.where(regionMask)).sel(time=slice(timespan[0], timespan[1])).sum(dim=reader.space_coord, 
                             ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'where'
```

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by jhardenberg**
## PR description:

This fixes the seaice volume and extend diagnostics which are currently failing as described in #2110
Indeed these diagnostics accumulated a quite impressive collection of bugs. The main one is their reference to a now not supported `grid_area` reader class property (we have only `src_grid_area` and `tgt_grid_area`). 
Then there were some issues with plotting and Dataset shapes (more mysterious where these come from)

Btw: I noticed that the reader initializes `grid_area` to Null but then never changes it again. Should we support it or remove it entirely?

## Issues closed by this pull request:

Close #2110 
Relevant for #2103 

----

 - [x] Changelog is updated.

### CODE REVIEW

**Comment by mnurisso** [comment]
Thanks, I'm merging this.
About grid_area I agree, an issue can be open about it.
