### ISSUE TITLE
Atmospheric global mean biases technical and scientific improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#561]
### Feature request

CLI introduced in #536 is going to be merged. Some error is present when trying to execute the CLI so we want to be sure it is not resulting in a problem in some plots production.

As a general comment the CLI seems to be very slow so that solving some of the technical issues below could be highly beneficial.

## Technical

- [ ] Add lon-lat/lev-lat grids (perhaps dashed) to plots

## Scientific
- [ ] Use contours to highlight the full field in the "difference" plots, so that only a single plot is provide for each variable. You could also move the statistics (as average, std, etc) in the same plot. RMSE can be added too
- [ ] Remove mtntrf (something like this in radiation diagnostics)
- [ ] Add statistical test for significance in difference plots to be showed with a stippling. a 95% confidence interval will be enough. This should be optional since I guess it will be computational heavy
        
<details>
<summary><b>Completed</b></summary>

These errors can be reproduced with the CLI introduced in #536 and the model-exp-source configured in the wrapper already introduced in the main in the folder `/cli/aqua-analysis`.

- [x] we get a `Warning: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()`. Some of the plot routines they have a `plt.show()` command embedded in the routine but this will not work when in a CLI and it may affect a bit the speed of the code. #587 
- [x] we get `An unexpected error occurred: Rectangle.set() got an unexpected keyword argument 'cmap'`. Notice that the error handling of this specific error is time consuming so it would be high priority to fix it. #587 
- [x] we get `KeyError occurred: 'plev'` #587
- [x] The analysis relies on the block:
```yaml
time_frame:
  start_date1: '2022-01-01'
  end_date1: '2023-12-31'
  start_date2: '2000-01-01'
  end_date2: '2020-12-31'
```
but the timespan to be analyzed should be not hardcoded in the configfile (running on 1990 simulations now will break the code) #587 
- [x] There is no logging, plain print should be removed in favor of the `aqua.logger` module #587 
- [x] we get  `Atmglobalmean CLI :: ERROR    -> An unexpected error occurred: can only convert an array of size 1 to a Python scalar` while running the `plot_map_with_stats` function #587
- [x] is `diagnostics/atmglobalmean/config.yaml` used or can it be removed?
- [x] timespan is now by default the entire available, shall we put an option to choose a specific timespan in the configfile (the one of the CLI so it's not hardcoded)?
- [x] Reduce filesize (too big PDFs)
- [x] Use more appropriate color scales, perhaps tuned for each diagnostic, and fix z-axis #812 
- [x] A bit of a philosophical issue: for the nextgems runs or other short and recent integrations I think the ERA5 reference period can be reduced including only the last 30 years perhaps

</details>
